<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Zion</RootNamespace>
    <AssemblyName>Zion</AssemblyName>
    <Product>Zion</Product>
    <Title>Zion</Title>
    <Version>1.0.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TestRunner" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Core\sing-box.gz" />
    <EmbeddedResource Include="Core\wintun.dll" />
    <Resource Include="Resources\Flags\*.png" />
    <Resource Include="app.ico" />
  </ItemGroup>

</Project>

